"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CDifUKX1hCY
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  ResizablePanelGroup,
  ResizablePanel,
  ResizableHandle,
} from "@/components/ui/resizable";

import { ChatUI } from "./chat";
import { GraphUI } from "./graph";
import { FileUploadUI } from "./file_upload";

export function Dashboard() {
  return (
    <div className="h-screen">
      <ResizablePanelGroup
        direction="horizontal"
        className="h-full items-stretch"
      >
        <ResizablePanel defaultSize={30}>
          <ChatUI />
        </ResizablePanel>

        <ResizableHandle withHandle />

        <ResizablePanel defaultSize={45}>
          <GraphUI />
        </ResizablePanel>

        <ResizableHandle withHandle />

        <ResizablePanel defaultSize={25}>
          <FileUploadUI />
        </ResizablePanel>
      </ResizablePanelGroup>
    </div>
  );
}
