KNN_MIN_SCORE = 0.94
CHUNK_BATCH_SIZE = 20

# EMBEDDING
MAX_PARALLEL_EMBEDDING_SIZE = 5
MAX_EMBEDDING_WORKER = 5

# How many chunk to combine to use in the graph generation
CHUNK_COMBINE_SIZE = 5
MAX_WORKERS = 5

VECTOR_EMBEDDING_DIMENSION = 768

FIRST_CHUNK = "FIRST_CHUNK"
NEXT_CHUNK = "NEXT_CHUNK"

TEMP_STORAGE = "temp_storage"
