CHAT_SEARCH_KWARG_K = 3
CHAT_SEARCH_KWARG_SCORE_THRESHOLD = 0.7
CHAT_DOC_SPLIT_SIZE = 3000
CHAT_EMBEDDING_FILTER_SCORE_THRESHOLD = 0.10
EMBEDDING_DIMENSION = 768

ANTHROPIC_MODEL_NAME = "claude-3-5-sonnet@20240620"
ANTHROPIC_REGION = "us-east5"
